# Generated by Django 3.0 on 2020-04-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_auto_20200421_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['title']},
        ),
    ]
