# Generated by Django 3.0 on 2020-05-06 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0004_auto_20200422_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('PR', 'Profile'), ('ED', 'Education'), ('EX', 'Experience'), ('WE', 'Work Experience'), ('WH', 'Work History'), ('PS', 'Personal Summary'), ('SU', 'Summary'), ('LA', 'Language'), ('OB', 'Objective'), ('SK', 'Skills'), ('KS', 'Key Skills'), ('AD', 'Additional Infomation')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
