# Generated by Django 3.0 on 2020-05-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0005_achievement_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['start_date']},
        ),
    ]
