# Generated by Django 3.0.6 on 2020-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
